FROM node:18.16.0-alpine3.18

LABEL maintainer="Ehsan Ghasaei"

COPY . /smart-contract
COPY package*.json /smart-contract

WORKDIR /smart-contract

EXPOSE 8545

RUN npm install -g npm@latest && \
    npm install -g truffle && \
    npm install

